title:            David Chon
description:      Turning Dreams into Reality
# put your disqus here
disqus_shortname: 
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: http://davidjchon.github.io

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  #- title: 'Tags'
  #  url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  # - title: 'Favorites'
  #   url: '#'
  #   submenu:
  #     - title: 'Code Highlighter'
  #       url: '/intro/code-highlighting-post/'
  #     - title: 'Sample Post'
  #       url: '/intro/sample-post/'
  - title: 'Download'
    url: '/David Chon Resume.pdf'
  - title: 'Resume'
    url: '/resume.html'

# Owner/author information
owner:
  name:           David Chon
  site:           http://davidjchon.github.io
  avatar:         images/avatar.jpg
  bio:            "I am a Mechanical Engineer interested in Design/Manufacturing and Materials/Structures.  I studied at UCR and graduated with a B.S. in Mechanical Engineering. Although I graduated as a Mechanical Engineer, I have some knowledge on many coding languages.  I hope to build strong relationships with those I encounter.  With my skills, I am confident that I can be a valuable asset to those work"
  email:          dchond@gmail.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter:  # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: davidjchon

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: 

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/davidjchon"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/dchond"
  - title: "youtube"
    url: "https://www.youtube.com/"
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/California
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
